# Generated by Django 4.1.7 on 2024-09-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0002_navegacion'),
        ('app_principal', '0003_navegacion'),
    ]

    operations = [
    ]
