# Generated by Django 4.1.7 on 2024-09-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_principal', '0005_evaluation_school_stage_student_evaluationindex_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaveProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
